name: "Class 1: Deploy Workflow"

on:
  pull_request:
    branches: [ main ]
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacer pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
