name: Class 5 Test Custom Action
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: JuanFelipeCano/actions-course@v1
        id: test-action
        with:
          who-to-greet: Juan Felipe

      - name: Sow actions output
        run: echo "Time - ${{ steps.test-action.outputs.time }}"

      # Assing the actions output to a variable
      - name: Sow actions output v2
        run: echo time "$TIME"
        shell: bash
        env:
          TIME: ${{ steps.test-action.outputs.time }}

      - name: Finish
        run: echo "Finished"
