name: "Class 2: Deploy to server"

# Sintexis de GitHub Actions:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

# El Contexto es una forma de acceder a la información de los Workflows
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs

on: push

jobs:
  first_job:
    # Nombre del job (visible al ejecutarse)
    name: First Job
    # Cada job necesita definir su ambiente de ejecución
    runs-on: ubuntu-latest
    # Definición de variables de entorno a nivel job
    env:
      NAME: JuanFelipe - JB

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo - Variable entorno $NAME"


  second_job:
    name: Second Job
    # Condicional para ejecutar el job solo cuando la referencia sea main
    if: ${{ github.ref == 'refs/heads/main' }}

    # Este job solo se ejecuta despues de ejecutar el first_job
    # Si first_job falla, este job no se ejecuta
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo job | ${{ github.ref }}"
