name: Class 5 Test Custom Action
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: JuanFelipeCano/jb-custom-greeting-action@v1
        with:
          who-to-greet: Juan Felipe

      - name: Finish
        run: echo "Finished"
