name: "Class 2: Deploy to server"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
    
  second_job:
    needs: first_job # Este job solo se ejecuta despues de ejecutar el first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo job"
