# Status check functions
# https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions

name: "Class 3: Deployment"

on: push

jobs:
  build:
    name: Run build and tests
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup node v18 environment
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Build project
      - name: Build
        run: npm run build

  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy
        run: echo "Deploying..."
    
