name: "Class 2: Deploy to server"

on:
  push:
    branches: [ main ]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
    
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo job"
