# Status check functions
# https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions

name: "Class 3: Deployment"

on: push

jobs:
  build:
    name: Run build and tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node: [ 18, 20 ]
    
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup node v18 environment
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm run test

      # 5. Build project
      - name: Build
        run: npm run build

      # 6. Upload artifact
      - name: Upload Artifact
        if: ${{ matrix.os == 'windows-latest' && matrix.node == 20 }}
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify:
    name: Notify
    needs: deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send notification
        run: echo "Notification status - ${{ job.status }}"
